puts "Clearing db..."
Gamestate.destroy_all
Location.destroy_all
Item.destroy_all

puts "Creating Locations"
L1 = Location.create(current_location: false, visited: false, name: "void", desc: "An endless space of darkness and mystery.", exits: "There are no exits.")
L2 = Location.create(current_location: false, visited: false, name: "gear", desc: "For wearing things.")
L3 = Location.create(current_location: false, visited: false, name: "inventory", desc: "the inside of your bag")
L4 = Location.create(current_location: false, visited: false, name: "bedroom", desc: "", exits: "")
L5 = Location.create(current_location: true, visited: false, name: "mountain peak", desc: "", exits: "There is a pathway leading down the mountain to the east.")
L6 = Location.create(current_location: false, visited: false, name: "mountain overlook", desc: "", exits: "The path continues down to the east, or you can go back up the way you came to the west.")
L7 = Location.create(current_location: false, visited: false, name: "mountain path", desc: "", exits: "A steep winding path leads the way to the south, or you can go back up the way you came to the west.")
L8 = Location.create(current_location: false, visited: false, name: "mountain path", desc: "", exits: "There is a dark cave entrance to the west, and the mountain path continues down to the east.")
L9 = Location.create(current_location: false, visited: false, name: "hidden cave", desc: "", exits: "The only way out is the way you came in, a rocky entrance to the east.")
L10 = Location.create(current_location: false, visited: false, name: "mountain path", desc: "stone archway", exits: "south, west")
L11 = Location.create(current_location: false, visited: false, name: "stone path", desc: "", exits: "north, south")
L12 = Location.create(current_location: false, visited: false, name: "lakeside path", desc: "", exits: "The path around the lake continues to the west and east.")
L13 = Location.create(current_location: false, visited: false, name: "lakeside path", desc: "", exits: "The path around the lake continues to the west and east.")
L14 = Location.create(current_location: false, visited: false, name: "lakeside path", desc: "", exits: "The path around the lake continues to the west and south, and branches off to the east.")
L15 = Location.create(current_location: false, visited: false, name: "lakeside path", desc: "", exits: "The path around the lake continues to the north and south.")
L16 = Location.create(current_location: false, visited: false, name: "lakeside path", desc: "", exits: "The path around the lake continues to the north and south, and a winding path through the trees leads off to the east.")
L17 = Location.create(current_location: false, visited: false, name: "lakeside path", desc: "", exits: "The path around the lake continues to the north and south.")
L18 = Location.create(current_location: false, visited: false, name: "lakeside path", desc: "", exits: "The path around the lake continues to the west and north.")
L19 = Location.create(current_location: false, visited: false, name: "lakeside path", desc: "", exits: "The path around the lake continues to the west and east.")
L20 = Location.create(current_location: false, visited: false, name: "lakeside path", desc: "", exits: "The path around the lake continues to the west and east.")
L21 = Location.create(current_location: false, visited: false, name: "lakeside path", desc: "", exits: "The path around the lake continues to the west and east.")
L22 = Location.create(current_location: false, visited: false, name: "lakeside path", desc: "", exits: "The path around the lake continues to the north and east.")
L23 = Location.create(current_location: false, visited: false, name: "lakeside path", desc: "", exits: "The path around the lake continues to the north and south.")
L24 = Location.create(current_location: false, visited: false, name: "lakeside path", desc: "", exits: "The path around the lake continues to the north and south.")
L25 = Location.create(current_location: false, visited: false, name: "lakeside path", desc: "", exits: "The path around the lake continues to the north and south.")
L26 = Location.create(current_location: false, visited: false, name: "lakeside path", desc: "", exits: "The path around the lake continues to the south and east.")
L27 = Location.create(current_location: false, visited: false, name: "lakeside path", desc: "", exits: "The path around the lake continues to the west and east.")
L28 = Location.create(current_location: false, visited: false, name: "lake", desc: "", exits: "")
L29 = Location.create(current_location: false, visited: false, name: "lake", desc: "", exits: "")
L30 = Location.create(current_location: false, visited: false, name: "lake", desc: "", exits: "")
L31 = Location.create(current_location: false, visited: false, name: "lake", desc: "", exits: "")
L32 = Location.create(current_location: false, visited: false, name: "middle of lake", desc: "", exits: "You can make out an outline of something at the bottom of the lake.")
L33 = Location.create(current_location: false, visited: false, name: "bottom of lake", desc: "", exits: "You can barely make out the surface of the lake above you.")
L34 = Location.create(current_location: false, visited: false, name: "lake", desc: "", exits: "")
L35 = Location.create(current_location: false, visited: false, name: "lake", desc: "", exits: "")
L36 = Location.create(current_location: false, visited: false, name: "lake", desc: "", exits: "")
L37 = Location.create(current_location: false, visited: false, name: "lake", desc: "", exits: "")
L38 = Location.create(current_location: false, visited: false, name: "stone path", desc: "", exits: "east, west")
L39 = Location.create(current_location: false, visited: false, name: "crossroads", desc: "", exits: "north, south, west")
L40 = Location.create(current_location: false, visited: false, name: "entrance to tower", desc: "", exits: "north, south")
L41 = Location.create(current_location: false, visited: false, name: "1st floor of tower", desc: "", exits: "south, up")
L42 = Location.create(current_location: false, visited: false, name: "top of tower", desc: "", exits: "down")
L43 = Location.create(current_location: false, visited: false, name: "path around cottage", desc: "", exits: "north, east, south")
L44 = Location.create(current_location: false, visited: false, name: "side of cottage", desc: "", exits: "east, west")
L45 = Location.create(current_location: false, visited: false, name: "side of cottage", desc: "", exits: "east, west")
L46 = Location.create(current_location: false, visited: false, name: "herb garden", desc: "", exits: "south, west")
L47 = Location.create(current_location: false, visited: false, name: "path to cottage", desc: "The winding pathway curves this way and that through the trees", exits: "You can go either west or east.")
L48 = Location.create(current_location: false, visited: false, name: "path to cottage", desc: "stone archway", exits: "north, east, south, west")
L49 = Location.create(current_location: false, visited: false, name: "cottage living room", desc: "", exits: "east, west")
L50 = Location.create(current_location: false, visited: false, name: "cottage kitchen", desc: "A warm kitchen, sunlight streams in through the windows. A table and chairs fit neatly into a corner. A wide woven rug is here.", exits: "west")
L51 = Location.create(current_location: false, visited: false, name: "cottage cellar", desc: "", exits: "up")
L52 = Location.create(current_location: false, visited: false, name: "behind the cottage", desc: "There is a well here.", exits: "north, south")
L53 = Location.create(current_location: false, visited: false, name: "path around cottage", desc: "", exits: "north, east")
L54 = Location.create(current_location: false, visited: false, name: "side of cottage", desc: "", exits: "east, south, west")
L55 = Location.create(current_location: false, visited: false, name: "side of cottage", desc: "", exits: "east, west")
L56 = Location.create(current_location: false, visited: false, name: "vegetable garden", desc: "", exits: "north, west")
L57 = Location.create(current_location: false, visited: false, name: "path to forest", desc: "stone archway", exits: "north, south")
L58 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "east, south")
L59 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "east, west")
L60 = Location.create(current_location: false, visited: false, name: "forest entrance", desc: "", exits: "west, east")
L61 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "east, south, west")
L62 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "south, west")
L63 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "north, east")
L64 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "east, south, west")
L65 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "east, west")
L66 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "north, west")
L67 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "north, south")
L68 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "east, south")
L69 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "north, west")
L70 = Location.create(current_location: false, visited: false, name: "forest clearing", desc: "", exits: "east, south")
L71 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "south, west")
L72 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "north, south")
L73 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "north, south")
L74 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "east, south")
L75 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "north, west")
L76 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "north, south")
L77 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "north, south")
L78 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "north")
L79 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "north, east")
L80 = Location.create(current_location: false, visited: false, name: "forest exit", desc: "", exits: "south, west")
L81 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "north, east")
L82 = Location.create(current_location: false, visited: false, name: "forest", desc: "", exits: "north, west")
L83 = Location.create(current_location: false, visited: false, name: "path to docks", desc: "", exits: "north, south")
L84 = Location.create(current_location: false, visited: false, name: "docks", desc: "", exits: "north, south")
L85 = Location.create(current_location: false, visited: false, name: "river by docks", desc: "", exits: "east")
L86 = Location.create(current_location: false, visited: false, name: "river", desc: "", exits: "east")
L87 = Location.create(current_location: false, visited: false, name: "river", desc: "", exits: "east")
L88 = Location.create(current_location: false, visited: false, name: "end of river", desc: "", exits: "east")

puts "Creating Items"
Item.create(location_id: 3, name: "towel", desc: "never leave home without a towel")
Item.create(location_id: 4, name: "key", desc: "A shiny brass key.")
Item.create(location_id: 5, name: "book", desc: "A leather bound book.")
Item.create(location_id: 6, name: "hat", desc: "A nice hat.")
Item.create(location_id: 7, name: "water bottle", desc: "Stay hydrated!")
Item.create(location_id: 8, name: "slice of cake", desc: "Looks delicious.")


puts "Creating Gamestates"
Gamestate.create(location_id: 5, output: "Welcome!")
Gamestate.create(location_id: 5, output: "If you need help, try typing \"help\".")
Gamestate.create(location_id: 5, output: "You have no idea where you are. Why don't you take a \"look\"?")

puts "Finished seeding!"
