puts "Clearing db..."
User.destroy_all
Gamestate.destroy_all
Item.destroy_all
Location.destroy_all

puts "Creating Locations"
L1 = Location.create(current_location: false, name: "void", desc: "An endless space of darkness and mystery.", exits: "There are no exits.")
L2 = Location.create(current_location: false, name: "gear", desc: "For wearing things.")
L3 = Location.create(current_location: false, name: "inventory", desc: "the inside of your bag")
L4 = Location.create(current_location: true, name: "bedroom", desc: "You are in a cozy bedroom. The bed has been piled with a warm comforter and fluffy pillows. Moonlight streams through the window, casting the room in shadows. The clock on the nightstand reads 2:34AM. A ghostly figure stands at the end of your bed, a translucent hand extended to you.", exits: "")
L5 = Location.create(current_location: false, name: "mountain peak", desc: "You are standing on top of a tall mountain. Wind gusts in from every direction, threatening to push you off the cliffs.", exits: "There is a pathway leading down the mountain to the east.")
L6 = Location.create(current_location: false, name: "mountain overlook", desc: "A flat rock juts over the side of the mountain, and from it you can see a verdant valley below you, surrounded on all sides by mountains. A tall tower is situated a ways to the east, and there is wide lake directly below you, sun glistening off the water. A distant cottage sits in a small clearing surrounded by forest, and beyond that to the south you can see a wide river.", exits: "The path continues down to the east, or you can head up to the mountain peak to the west.")
L7 = Location.create(current_location: false, name: "mountain path", desc: "The path is narrow and dangerous, with steep drops off the side. You carefully mind your steps.", exits: "The treacherous path curves to way to the south, or you can head up the mountain to the west.")
L8 = Location.create(current_location: false, name: "mountain path", desc: "A bend in the path reveals a dark jagged hole in the side of the mountain to the west, daring you enter the darkness.", exits: "The mountain path continues down to the east and up to the north.")
L9 = Location.create(current_location: false, name: "hidden cave", desc: "The weak glow from your lantern barely lights your nearby surroundings, let alone the entire expanse of the wide cave. Strange whispers and the rustling of unseen things echo from the depths, making the hairs on the back of your neck stand on end. Some distance from the entrance you see a marble basin upon a large stone table. It seems widly out of place here.", exits: "The only way out that you can see is the way you came in, a rocky entrance to the east.")
L10 = Location.create(current_location: false, name: "archway", desc: "A stone archway stands tall here, seemingly carved straight out of the mountains. Six gemstones have been affixed to the archway's pillars, but there's an empty slot where a seventh could be. A forcefield radiates off the archway, blocking your path south.", exits: "A dirt path leads to westward to the mountain, and a stone path leads south through the archway.")
L11 = Location.create(current_location: false, name: "stone path", desc: "Colorful flowers dot the fields on either side of the path. Birdsong filters through the air.", exits: "The mountains tower above towards the north, and the lake lies to the south.")
L12 = Location.create(current_location: false, name: "stone path", desc: "A rainbow arcs overhead, landing into the glistening blue lake before you. There is a sign here forbidding swimming.", exits: "A path around the lake continues to the west and east.")
L13 = Location.create(current_location: false, name: "stone path", desc: "The smooth stone path feels wonderful on your barefeet.", exits: "The path around the lake continues to the west and east.")
L14 = Location.create(current_location: false, name: "stone path", desc: "You can see the tower to the east, the top of it poking out above the treeline, and the lake lies to the southwest.", exits: "The path around the lake continues to the west and south, and another path branches off to the east.")
L15 = Location.create(current_location: false, name: "stone path", desc: "The lake mirrors the fluffy clouds high above.", exits: "The path around the lake continues to the north and south.")
L16 = Location.create(current_location: false, name: "stone path", desc: "Willow trees dot the shoreline, branches dipping into the lake shallows.", exits: "The path around the lake runs north to south, and a winding path through the trees leads off to the east.")
L17 = Location.create(current_location: false, name: "stone path", desc: "The sun sparkles off the water, reflecting the puffy clouds above.", exits: "The path around the lake continues to the north and south.")
L18 = Location.create(current_location: false, name: "stone path", desc: "The water looks inviting, crystal clear and cool. A sparrow flies about happily, enjoying life.", exits: "The path around the lake continues to the west and north.")
L19 = Location.create(current_location: false, name: "stone path", desc: "A simple wooden bench sits here, overlooking the lake.", exits: "The path around the lake continues to the west and east.")
L20 = Location.create(current_location: false, name: "stone path", desc: "The valley begins to slopes southward. You can see a dark forest between you and the river, but you cannot see a way to get to the forest from here.", exits: "The path around the lake continues to the west and east.")
L21 = Location.create(current_location: false, name: "stone path", desc: "The cattails flutter in the wind by the lake.", exits: "The path around the lake continues to the west and east.")
L22 = Location.create(current_location: false, name: "stone path", desc: "Insects hum gently by the waterside.", exits: "The path around the lake continues to the north and east.")
L23 = Location.create(current_location: false, name: "stone path", desc: "The air here is filled with the scent of wildflowers that line the lake.", exits: "The path around the lake continues to the north and south.")
L24 = Location.create(current_location: false, name: "stone path", desc: "The lake reflects the sky and surrounding forest like a painting come to life.", exits: "The path around the lake continues to the north and south.")
L25 = Location.create(current_location: false, name: "stone path", desc: "Willow trees line the shore, branches moving slowly with the breeze.", exits: "The path around the lake continues to the north and south.")
L26 = Location.create(current_location: false, name: "stone path", desc: "The water laps gently at the edge of the lake.", exits: "The path around the lake continues to the south and east.")
L27 = Location.create(current_location: false, name: "stone path", desc: "Far above you can see the mountain you walked down.", exits: "The path around the lake continues to the west and east.")
L28 = Location.create(current_location: false, name: "lake", desc: "You luxuriate in the feeling of the cold water as you swim.", exits: "The shoreline lies to the north and west of you.")
L29 = Location.create(current_location: false, name: "lake", desc: "You swim in a shallow part of the lake, sun shining off the top.", exits: "The shore lies directly north.")
L30 = Location.create(current_location: false, name: "lake", desc: "Cold, clear water surrounds you as you swim in the lake.", exits: "The shoreline lies to the north and east of you.")
L31 = Location.create(current_location: false, name: "lake", desc: "Your bare feet brush smooth stones as you swim in the shallows.", exits: "The shore lies directly west.")
L32 = Location.create(current_location: false, name: "middle of lake", desc: "You tread water in the middle of the lake. It's fairly deep here, the water less clear.", exits: "You make out an outline of something large at the bottom of the lake.")
L33 = Location.create(current_location: false, name: "bottom of lake", desc: "You hold your breath, swimming at the bottom of the lake. It's murky and eerily quiet here, cold water surrounds you. There's an old sunken shipwreck here, deteriorating into the mud. You can see a locked wooden chest nestled in the bowels of the ship.", exits: "You can barely make out the surface of the lake above you.")
L34 = Location.create(current_location: false, name: "lake", desc: "Sun beats down on your shoulders as you swim in the shallows.", exits: "The shore lies directly east.")
L35 = Location.create(current_location: false, name: "lake", desc: "With strong strokes, you swim through the water.", exits: "The shoreline lies to the south and west of you.")
L36 = Location.create(current_location: false, name: "lake", desc: "You feel refreshed as you swim in the southern part of the lake.", exits: "The shore lies directly south.")
L37 = Location.create(current_location: false, name: "lake", desc: "You are amazed at how clear the water is as you swim in the shallows.", exits: "The shoreline lies to the east and south of you.")
L38 = Location.create(current_location: false, name: "stone path", desc: "A breeze smelling of wildflowers wafts over you from the verdant green valley to the north. Trees dot the landscape.", exits: "The stone path runs east to west here.")
L39 = Location.create(current_location: false, name: "crossroads", desc: "You are at a crossroads.", exits: "To the south the cottage sits nestled in a small clearing surrounded by forest. To the north, a tall tower juts out of the earth and points towards the sky. To the west, the stone path leads to the lake.")
L40 = Location.create(current_location: false, name: "entrance to the tall tower", desc: "The stone tower rises out of the earth like a beacon in the forest. It's made from rough-hewn stone blocks, and the windows have been intricately created from colorful stained glass. There is a grumpy wizard here, rocking in a chair by the door. He hums to himself and eyes you suspiciously.", exits: "To the north is a large wooden door, or you can go south towards the crossroads.")
L41 = Location.create(current_location: false, name: "first floor of the wizard's tower", desc: "The windowless room is filled to the brim with magical artifacts, books, potions, dried herbs, and plants you don't recognize. A large fire crackles in the hearth, casting the room in a warm glow.", exits: "The door to the south leads outside and a rickety spiral staircase winds its way up.")
L42 = Location.create(current_location: false, name: "top of the wizard's tower", desc: "The spiral staircase seems go on forever, but you finally reach the top. The mountains loom all around you, and you can see the river towards the south, a dense forest separating it from the rest of the valley and you. You can make out a boat bobbing in the water at the docks. You wonder if the boat could take you back home.", exits: "An opened trapdoor shows the top of the spiral staircase leading downstairs.")
L43 = Location.create(current_location: false, name: "path around cottage", desc: "You are walking along a narrow path between the stone cottage and the wizard tower.", exits: "The path to the tower heads to the north, or you can go south to the front door of the cottage. You see an herb garden behind the cottage to the east.")
L44 = Location.create(current_location: false, name: "side of cottage", desc: "Various tools are proppped against the wall of the cottage.", exits: "You can walk around the cottage to the west or east.")
L45 = Location.create(current_location: false, name: "side of cottage", desc: "Clean linens and clothing dry patiently on a laundry line.", exits: "You can go either east or west.")
L46 = Location.create(current_location: false, name: "herb garden", desc: "There is an an herb garden here, peaceful and fragrant. There are neat rows of basil, thyme, rosemary, chamomile, and lavendar.", exits: "A well and vegetable garden are towards the south, or you could go west where laundry hangs on the line.")
L47 = Location.create(current_location: false, name: "path to cottage", desc: "The winding pathway curves this way and that. Cheerful birdsong filters down through the trees.", exits: "You can go either west or east.")
L48 = Location.create(current_location: false, name: "path to cottage", desc: "You are in a small clearing, a small cottage nestled within. Towards the back you see gardens and fresh laundry fluttering in the breeze.", exits: "The entrance to the cottage is directly east, but the door is missing a doorknob. Towards the north you spot the tower, to the south the wide forest resides, and another path winds westward through the trees.")
L49 = Location.create(current_location: false, name: "cottage living room", desc: "The inside of the cottage is warm and inviting. The living room is filled with an overstuffed sofa and a worn rocking chair. A fire crackles in a stone hearth.", exits: "The front door of the cottage opens westward, and the kitchen is through the east door.")
L50 = Location.create(current_location: false, name: "cottage kitchen", desc: "The kitchen is cozy and rustic. A table sits in the corner, surrounded by chairs with seat cushions in a cheerful floral print. Large bay windows overlook the gardens and let in streams of sunlight that dance throughout the room. A worn woven rug covers the floor.", exits: "The living room is to the west.")
L51 = Location.create(current_location: false, name: "cottage cellar", desc: "The cellar is cool and dark. It's cluttered with a wide assortment of odds and ends, including old crates, barrels of vegetables and sacks of dried goods.", exits: "A narrow staircase leads the way back up.")
L52 = Location.create(current_location: false, name: "behind the cottage", desc: "There is a well here.", exits: "An herb garden has been planted towards the north, and a vegetable garden flourishes to the south.")
L53 = Location.create(current_location: false, name: "path around cottage", desc: "There's a pile of wood and a chopping block here, an axe buried into the stump of a fallen tree.", exits: "You can go north to the front of the cottage or east towards the back.")
L54 = Location.create(current_location: false, name: "side of cottage", desc: "Wildflowers line the edge of the clearing, smelling sweet in the air.", exits: "The path around the cottage runs west to east, or you can head down a rocky path southwards towards the forest.")
L55 = Location.create(current_location: false, name: "side of cottage", desc: "A little table and two chairs sit against the cottage.", exits: "You can go either east or west.")
L56 = Location.create(current_location: false, name: "vegetable garden", desc: "The vegetable garden is a thriving plot of dirt and healthy plants. Bright red tomatoes flourish next to perfectly round melons, and a wooden trellis supports climbing peas.", exits: "A well sits to the north, and you can go west towards the front of the cottage.")
L57 = Location.create(current_location: false, name: "path to forest", desc: "The forest looms above you. It's dark and menacing. You'd rather not go into it. A terrifying tree spirit blocks your way south.", exits: "The path climbs northward to the cottage or southward into the forest.")
L58 = Location.create(current_location: false, name: "forest", desc: "Tightly packed trees tower on each side of you. Tiny glowing mushrooms sprout from the earth.", exits: "You can vaguely make out the pathway that continues east and south.")
L59 = Location.create(current_location: false, name: "forest", desc: "The forest is densely packed. It feels like it might suffocate you.", exits: "The dirth path runs east to west.")
L60 = Location.create(current_location: false, name: "forest entrance", desc: "The eery quiet of the forest surrounds you.", exits: "To the north lies a path out of the forest, or you can go deeper west or east, and a fallen log makes a bridge over a deep ravine to the south.")
L61 = Location.create(current_location: false, name: "forest", desc: "Towering trees line either side of the path, vines cutting back and forth across the way.", exits: "It looks like someone tried to cut a path towards the east. The dirt path ends here and picks back up to the west.")
L62 = Location.create(current_location: false, name: "forest", desc: "You think you might be lost. Should you go back the way you came?", exits: "No path exists here, but you can make out trampled bushes towards the south.")
L63 = Location.create(current_location: false, name: "forest", desc: "You think you hear a woman singing, the song is dreadfully sad and haunting. Dark forest surrounds you.", exits: "The path curves north to east here.")
L64 = Location.create(current_location: false, name: "forest", desc: "You come across a crossroads in the forest.", exits: "You can go east, south, or west.")
L65 = Location.create(current_location: false, name: "forest", desc: "You think you can hear a child laughing, somewhere deep in the forest.", exits: "The path runs east to west, and a fallen log makes a bridge over a deep ravine to the north.")
L66 = Location.create(current_location: false, name: "forest", desc: "The tree canopy is so thick you cannot see a single speck of sky.", exits: "The trail ends here, the only way back is to the west.")
L67 = Location.create(current_location: false, name: "forest", desc: "Laughter echoes through the trees, deep and menacing.", exits: "A vague trail has appeared here, running north to south.")
L68 = Location.create(current_location: false, name: "forest", desc: "Only a few specks of sky are visible through the dense treeline. You feel trapped.", exits: "You can see the path leading east and south.")
L69 = Location.create(current_location: false, name: "forest", desc: "The dense canopy creates a sense of unease, as if the forest is hiding secrets within.", exits: "The path disappears for a moment but you eventually find it again, continuing on to the north and west.")
L70 = Location.create(current_location: false, name: "forest clearing", desc: "You are standing in a grassy meadow, tall trees line the perimeter. The eye in a storm of forest.", exits: "You can make out paths leading east and south.")
L71 = Location.create(current_location: false, name: "forest", desc: "You are grateful for your compass. The dense foliage has you completely turned around.", exits: "You can go either south or west here.")
L72 = Location.create(current_location: false, name: "forest", desc: "The forest has become eerily quiet. A sense of dread comes over you. Will you ever find your way out?", exits: "The forest path lies north to south.")
L73 = Location.create(current_location: false, name: "forest", desc: "The trees tower above you, hiding any remaining sight of sky from you.", exits: "Only a hint of the path remains, going north to south.")
L74 = Location.create(current_location: false, name: "forest", desc: "You feel as though you've been in this forest for days, or maybe weeks. Will you ever get out again?", exits: "You think you can go east, or maybe south.")
L75 = Location.create(current_location: false, name: "forest", desc: "A deep ravine lies to the south. You think you can here vague moans echoing from it's depths, but it's deep enough that you cannot see the bottom.", exits: "You can see a clearing to the north, and the path continues to the west.")
L76 = Location.create(current_location: false, name: "forest", desc: "You think you might be going deeper into the forest. Surely this isn't the right way.", exits: "You see two openings through the trees, one to the north and another to the south.")
L77 = Location.create(current_location: false, name: "forest", desc: "A tree has fallen across the path here. Mushrooms grow out of the decaying wood.", exits: "The path leads either north or south.")
L78 = Location.create(current_location: false, name: "forest", desc: "A dead end. The path ends abruptly and the feeling of being lost makes you want to scream.", exits: "The only direction you can go is north, and you edge desperately back towards it.")
L79 = Location.create(current_location: false, name: "forest", desc: "You see a few streams of sunlight filter through the trees towards the east.", exits: "The path here curves north to east.")
L80 = Location.create(current_location: false, name: "forest exit", desc: "You sigh with relief as you finally find your way out of the forest.", exits: "A wide gap in the trees leads south towards a river. A path leads back into the forest to the west.")
L81 = Location.create(current_location: false, name: "forest", desc: "Foul smelling mud comes up to your ankles, and it takes effort to wade through to the other side.", exits: "You can go either north or east here.")
L82 = Location.create(current_location: false, name: "forest", desc: "A bend in the forest path curves through the towering trees.", exits: "You can go either north or west here.")
L83 = Location.create(current_location: false, name: "path to docks", desc: "The forest looms to the north as you follow the path, cutting through a flower filled meadow.", exits: "The river is to your south, the path ending at a wooden dock.")
L84 = Location.create(current_location: false, name: "docks", desc: "The dock extends out onto the wide river, the water dark and slow moving. A single rowboat is moored at the side.", exits: "You can go north towards the forest, or south into the rowboat.")
L85 = Location.create(current_location: false, name: "rowboat", desc: "You get into the rowboat and push off from the docks. Unlike the lake, the water is murky and eery, the current bears you downriver.", exits: "The river heads eastward.")
L86 = Location.create(current_location: false, name: "river", desc: "The docks disappear from view as you make your way downriver.", exits: "There is no going back now, as water bears you downriver to the east.")
L87 = Location.create(current_location: false, name: "river", desc: "The river curves through a wide valley, tall mountains rising on either side of you.", exits: "The river has picked up speed, carrying you still eastward.")
L88 = Location.create(current_location: false, name: "end of river", desc: "A moment too late, you see the end of the river ends in a waterfall, and you cannot row against the current.", exits: "You can only go east.")
L89 = Location.create(current_location: false, name: "dream crossroads", desc: "You float in an endless sea of stars. Swirls of light and color surround you.", exits: "An elegantly carved wooden door floats before, just waiting to be opened.")
L90 = Location.create(current_location: false, name: "top of mountain", desc: "You lie on your back, staring up at a vibrantly blue sky. You have vague recollections of falling to your death, but you feel fine.", exits: "Perhaps you should \"stand up\" first.")
L91 = Location.create(current_location: false, name: "river waterfall", desc: "The rowboat tips over the edge of the waterfall, and you scream as you fall. Everything seems to be moving in slow motion. You can see nothing except water, all around you.", exits: "You can only go down.")
L92 = Location.create(current_location: false, name: "bedroom2", desc: "You are in a cozy bedroom. The bed has been piled with a warm comforter and fluffy pillows. Moonlight streams through the window, casting the room in shadows. The clock on the nightstand reads 4:15AM.", exits: "You have work in the morning. Perhaps you should get some sleep.")

puts "Creating Items"
I1 = Item.create(location_id: 8, name: "lantern", desc: "A dimly lit lantern.")
I2 = Item.create(location_id: 9, name: "basin", desc: "A large mable basin filled with black liquid.")
I3 = Item.create(location_id: 24, name: "key", desc: "A shiny brass key.")
I4 = Item.create(location_id: 1, name: "ruby", desc: "A bloodred ruby.")
I5 = Item.create(location_id: 33, name: "doorknob", desc: "A golden doorknob.")
I6 = Item.create(location_id: 45, name: "swimsuit", desc: "A striped, colorful thing.")
I7 = Item.create(location_id: 89, name: "compass", desc: "An antique compass, it's fairly accurate.")
I8 = Item.create(location_id: 5, name: "hat", desc: "A nice hat.")
I9 = Item.create(location_id: 55, name: "slice of cake", desc: "Looks delicious.")
I10 = Item.create(location_id: 19, name: "towel", desc: "A towel is one of the most useful things you can carry.")
I11 = Item.create(location_id: 41, name: "book", desc: "A leather bound book. The dedication reads: \"This little game was created during my time at Flatiron's Software Engineering Bootcamp. Many thanks to all the help received along the way including: \"")
I12 = Item.create(location_id: 42, name: "empty bucket", desc: "A wooden bucket for carrying water. It's empty.")
I13 = Item.create(location_id: 51, name: "jar of pickles", desc: "A glass jar of preserved pickles. I hear wizards love these.")
I14 = Item.create(location_id: 40, name: "wizard", desc: "He's a wizard, probably. You remember you once heard that wizards love pickles.")
I15 = Item.create(location_id: 1, name: "bucket of water", desc: "A bucket filled with water.")
I16 = Item.create(location_id: 57, name: "tree spirit", desc: "A cute tree spirit, dancing in the wind.")
I17 = Item.create(location_id: 4, name: "ghost figure", desc: "A tall ghost with spindly arms. One hand is extended to you. You can't see its face, nor would you want to.")
I18 = Item.create(location_id: 18, name: "sparrow bird", desc: "A pretty bird, with an even prettier song.")
I19 = Item.create(location_id: 1, name: "ghost of a sparrow bird", desc: "Ghost of the sparrow you murdered. It looks at you with sad eyes.")
I20 = Item.create(location_id: 2, name: "pajamas", desc: "Your pajamas are quite soft.")
I21 = Item.create(location_id: 50, name: "rug", desc: "A nicely woven rug. It seems to be covering something, you wonder what might be underneath.")
I22 = Item.create(location_id: 52, name: "well", desc: "A stone well. It's missing a bucket.")
I23 = Item.create(location_id: 33, name: "chest", desc: "A waterlogged old wooden chest. There's a rusted keyhole on the front.")
I24 = Item.create(location_id: 10, name: "archway", desc: "A beautiful stone archway, six gemstones have been placed on the archway, but it's missing a seventh. A forcefield hums around it.")

# puts "Creating Users"
# User.create(username: "admin", password: "123")

# puts "Creating Gamestates"
# Gamestate.create(location_id: 4, user_id: U1.id, output: "Welcome to Dreamland.")
# Gamestate.create(location_id: 4, user_id: U1.id, output: "If you need help, try typing \"help\" and then hit enter.")
# Gamestate.create(location_id: 4, user_id: U1.id, output: "You are half asleep in bed. Moonlight streams through the window, casting the room in shadows. The clock on your nightstand reads 2:34AM. A ghostly figure stands at the end of your bed, a translucent hand extended to you.")

puts "Finished seeding!"
